### ISSUE TITLE
Handle common issues on import

### ISSUE THREAD

**Issue by slaporte** [hatnote/montage#141]
When a coordinator imports files, Montage should:

- [ ] warn about deleted files #30 
- [ ] resolve moved files #97 
- [ ] resolve full Wikimedia Commons URLs
- [ ] resolve URL encoding issues
- [ ] resolve common typos (spaces or underscores at the beginning or end of the filename)
- [ ] warn users when files are not imported #108 
- [ ] save a log of files that were not imported #108  
- [ ] provide an easy tool to figure out which files from your source list are not in the round #140 
- [ ] ensure there are no `duplicate entry` errors #146
